index.html

Add a new section to the Use Cases document called "Focal Use Cases" that will demonstrate how VC address evidence of applicability by solving complex market needs.

Focal uc structure

---

README.md

update chair list

---

index.html

Update Company reference for Joe Andrieu

update Joe Andrieu company

---

index.html

move JoeA from author to editor
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/61.html" title="Last updated on May 15, 2018, 5:13 PM GMT (39be432)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/61/94d6f67...39be432.html" title="Last updated on May 15, 2018, 5:13 PM GMT (39be432)">Diff</a>

move JoeA to editor

---

index.html

Promoted Matt Stone and Tzviya Siegman from document authors to editors.

Move Stone and Siegman from author to editor

---

index.html

Add the Citizenship Focal Use Case and the first couple of threats in the Threat Model.  Let's validate Threat Model formatting before I add them all.
***
<a href="https://pr-preview.s3.amazonaws.com/stonematt/vc-use-cases/pull/63.html" title="Last updated on May 15, 2018, 9:01 PM GMT (93128d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/63/6ee1851...stonematt:93128d2.html" title="Last updated on May 15, 2018, 9:01 PM GMT (93128d2)">Diff</a>

Add Citizenship Focal Use Case

---

index.html

add line breaks at column 100
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/66.html" title="Last updated on May 24, 2018, 4:05 PM GMT (4e6b81b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/66/e487ebf...4e6b81b.html" title="Last updated on May 24, 2018, 4:05 PM GMT (4e6b81b)">Diff</a>

editorial: line wrap at 100char

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/67.html" title="Last updated on May 24, 2018, 8:23 PM GMT (1f68fd5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/67/69093e1...1f68fd5.html" title="Last updated on May 24, 2018, 8:23 PM GMT (1f68fd5)">Diff</a>

Move subject != holder to distinction section

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/68.html" title="Last updated on May 24, 2018, 8:25 PM GMT (3b0aa32)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/68/69093e1...3b0aa32.html" title="Last updated on May 24, 2018, 8:25 PM GMT (3b0aa32)">Diff</a>

Update threats in traveler use case

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/72.html" title="Last updated on Jun 7, 2018, 4:55 PM GMT (f166f9f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/72/feab877...f166f9f.html" title="Last updated on Jun 7, 2018, 4:55 PM GMT (f166f9f)">Diff</a>

Fix typo for issue #56

---

index.html

fixes issue #76  and fixes issue #3
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/81.html" title="Last updated on Jul 27, 2018, 9:53 PM GMT (041c530)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/81/2b46e91...041c530.html" title="Last updated on Jul 27, 2018, 9:53 PM GMT (041c530)">Diff</a>

complete editorial changes for issue 76

---

index.html

fixes #6
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/82.html" title="Last updated on Jul 27, 2018, 10:14 PM GMT (fffa9f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/82/684b6f8...fffa9f4.html" title="Last updated on Jul 27, 2018, 10:14 PM GMT (fffa9f4)">Diff</a>

Fix usage of dash and emdash

---

index.html

fixes issue #5
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/84.html" title="Last updated on Jul 27, 2018, 10:39 PM GMT (382b961)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/84/b44fc75...382b961.html" title="Last updated on Jul 27, 2018, 10:39 PM GMT (382b961)">Diff</a>

Update definition of holder to match Datamodel

---

index.html

fixes issue #2
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/83.html" title="Last updated on Jul 27, 2018, 10:33 PM GMT (99a5926)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/83/b44fc75...99a5926.html" title="Last updated on Jul 27, 2018, 10:33 PM GMT (99a5926)">Diff</a>

Restate details of Store/Move Claim

---

index.html

Content from @David-Chadwick and @dlongley in the data model issue https://github.com/w3c/vc-data-model/issues/187
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/86.html" title="Last updated on Oct 2, 2018, 2:51 PM GMT (b976448)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/86/749785f...b976448.html" title="Last updated on Oct 2, 2018, 2:51 PM GMT (b976448)">Diff</a>

Add example for International Travel with Minor

---

index.html

fixes issue https://github.com/w3c/vc-data-model/issues/200 raced by @CipherQueen

Update link to common glossary

---

index.html

fixes #94 - Added use case R.3 Fraud detection
***
<a href="https://pr-preview.s3.amazonaws.com/RieksJ/vc-use-cases/pull/98.html" title="Last updated on May 9, 2019, 7:13 AM UTC (2916ac7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/98/2b333c6...RieksJ:2916ac7.html" title="Last updated on May 9, 2019, 7:13 AM UTC (2916ac7)">Diff</a>

fixes #94 - Added use case R.3 Fraud detection

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/101.html" title="Last updated on Jun 28, 2019, 4:37 PM UTC (e6bab44)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/101/2b333c6...e6bab44.html" title="Last updated on Jun 28, 2019, 4:37 PM UTC (e6bab44)">Diff</a>

adds use case from RieksJ, fixes terminology

---

index.html

getting ready to update the domain map.  ordering this section to reflect the charter priorities.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/102.html" title="Last updated on Jun 28, 2019, 7:14 PM UTC (38ca8b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/102/4cd39e9...38ca8b7.html" title="Last updated on Jun 28, 2019, 7:14 PM UTC (38ca8b7)">Diff</a>

Update order of User Needs

---

index.html

This should be a straightforward addition of work done in the Use Case team over the last couple months. Comments & feedback welcome.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/100.html" title="Last updated on Aug 13, 2019, 2:12 PM UTC (617b929)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/100/1f0f079...617b929.html" title="Last updated on Aug 13, 2019, 2:12 PM UTC (617b929)">Diff</a>

added PADI focal use case

---

index.html

Updates terms. fixes #108
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/112.html" title="Last updated on Aug 25, 2019, 8:35 PM UTC (5cd6353)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/112/44f489e...5cd6353.html" title="Last updated on Aug 25, 2019, 8:35 PM UTC (5cd6353)">Diff</a>

Define terms

---

index.html

Several questions in doc as "issues" were hang overs from previous discussions.  Clean them up.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 31, 2019, 4:25 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fvc-use-cases%2F37a7e0aad7ae6bde8d7db4160a419a03042509f7%2Findex.html%3FisPreview%3Dtrue)
```
Navigation Timeout Exceeded: 30000ms exceeded
```
_If you don't have enough information …

Cleanup Issue Notes

---

index.html

Cleaning up editor and author lists
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/pull/113.html" title="Last updated on Sep 6, 2019, 2:09 AM UTC (f160993)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/113/37a7e0a...f160993.html" title="Last updated on Sep 6, 2019, 2:09 AM UTC (f160993)">Diff</a>

Update Editor/Author sections

---

index.html

Signed-off-by: Kenneth Ebert <ken@kindredlearning.com>
***
<a href="https://pr-preview.s3.amazonaws.com/ken-ebert/vc-use-cases/pull/118.html" title="Last updated on Sep 10, 2019, 8:37 PM UTC (8ebdb43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/118/a2ac4d3...ken-ebert:8ebdb43.html" title="Last updated on Sep 10, 2019, 8:37 PM UTC (8ebdb43)">Diff</a>

remove duplicate figure 2, Amanda->Anand

---

index.html

Fixes: #158
***
<a href="https://pr-preview.s3.amazonaws.com/laysakura/vc-use-cases/pull/159.html" title="Last updated on Jul 20, 2024, 1:41 AM UTC (bd31e38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-use-cases/159/c69ef3e...laysakura:bd31e38.html" title="Last updated on Jul 20, 2024, 1:41 AM UTC (bd31e38)">Diff</a>

docs(fix): mistakes in Figure 2
